{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel.serviceAccountName" . }}
  labels:
{{ include "sentinel.labels" . | nindent 4 }}
{{- end -}}
