---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "polygon-daemon.fullname" . }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: fast-storage