---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polygon-daemon.fullname" . }}
  labels:
    {{- include "polygon-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service }}
  {{- range $nodeName, $ports := .Values.ports }}
  {{- range $portIndex, $port := $ports }}
  ports:
  - name: {{ $port.name }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.name }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "polygon-daemon.selectorLabels" . | nindent 4 }}