#values file for the polygon node

replicas: 1
configMap: scripts-cm

# filesystemId for the storage class
fileSystemId: ""

chain: mainnet

nameOverride: ""
fullnameOverride: ""

images:
  heimdall: 
    name: 0xpolygon/heimdall
    tag: "0.3.4"
  bor:
    name: 0xpolygon/bor
    tag: "0.4.0"

volumeMount:
  heimdall:
    path: /heimdall-home
  bor:
    path: /bor-home

env:
  heimdall:
  - name: SNAPSHOT_URL
    # https://snapshot-download.polygon.technology/heimdall-mainnet-incremental-compiled-files.txt
    value: "" 
  - name: BOOTSTRAP
    # 0 to not bootstrap (use snapshots), 1 to bootstrap
    value: "0" 
  - name: ETH_RPC_URL
    # e.g., https://nd-123-456-789.p2pify.com/60f2a23810ba11c827d3da642802412a
    value: "" 
  - name: SEEDS
    # e.g, f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,902484e868c6a4bace1bb3cf4b6ba1667561b158@18.228.218.160:26656,afc41bd37d549186cec915c5a4feb3071871cdc1@18.228.98.237:26656,587df41fb0198d72a9e153c608b2c0d840551429@35.182.147.162:26656,ad7bc1c45641454893c74b50357a1bd87778bb50@52.60.36.93:26656
    value: "" 
  - name: BOR_RPC_URL
    value: "http://localhost:8545"
  bor:
  - name: BOOTSTRAP
    value: "0" # 0 to not bootstrap (use snapshots), 1 to bootstrap
  - name: BOOTNODES
    # e.g., '"enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"' the single quote is used as an escape character
    value: '""' 
  - name: SNAPSHOT_URL
    # https://snapshot-download.polygon.technology/bor-mainnet-incremental-compiled-files.txt
    value: "" 
  - name: HEIMDALL_RPC
    value: "http://localhost:26657/status"
  - name: HEIMDALL_REST
    value: '"http://localhost:1317"'

ports:
  heimdall:
  - name: heimdall-p2p
    containerPort: 26656
  - name: heimdall-rpc
    containerPort: 26657
  - name: restapi
    containerPort: 1317
  bor:
  - name: bor-p2p
    containerPort: 30303
  - name: bor-rpc
    containerPort: 8545

service: ClusterIP
storage: 4000Gi

resources:
  limits:
    # cpu: 16
    memory: 16Gi
  requests:
    cpu: 1
    memory: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}